version: '3.8'

services:
    front:
        container_name: react
        build:
            context: .
            args: # from .env file
                NODE_VERSION: ${NODE_VERSION}
                NPM_VERSION: ${NPM_VERSION}
        environment:
            NODE_ENV: ${NODE_ENV}
            REACT_APP_STRIPE_PUBLISHABLE_API_KEY: ${STRIPE_PUBLISHABLE_API_KEY}
            REACT_APP_API_URL: ${API_URL}
        ports:
            - '3000:3000'
        volumes:
            - .:/home/node/reactmeadr.ink:delegated